app/mc.md Add Java版MC服务端开服指引
natfrp/wiki pull request #432
Opened 2024-02-04 06:48 UTC by zymooll

是 #431 的补充版本。原 pr 已关闭。

2024-02-04 08:39 UTC, fakeboboliu requested changes
非常感谢您的贡献，
尽管各地的教程已经很多了，但是在官方文档中包括这个话题是一段很重要的补充。

您的文档书写风格比较随意，
为了在这篇文档的上下文中更加和谐，这个 PR 的内容需要就行文和排版做出一些修改。

如果您愿意亲力亲为，您可以参考我的评论和其他文档进行修改；
如果您比较忙碌的话，我也可以进行一下这些修改，最终的作者名单仍然会出现您的名字。

2024-02-04 08:39 UTC, fakeboboliu commented on app/mc.md
> +一般推荐 1.13 以下用 Java 8，1.13 及以上用 Java 18。
根据一些常见的认知来说，
1.12 以下应该考虑使用 Java 8，
而 1.17 前的 forge server 很多对于新版 Java 有兼容性问题，这些也应该使用 Java 8。

更新到 Java 21 通常能提供一点性能提升，
官方文档也通常会表示 or newer，或许应该推荐优先尝试？

2024-02-04 08:39 UTC, fakeboboliu commented on app/mc.md
> +首先我们先下载对应版本的 Java，推荐国内用户前往 [Java 官网](https://www.java.com/zh-CN/download/) 下载 Java8，前往 [微软构建的 Openjdk18](https://learn.microsoft.com/zh-cn/java/openjdk/download) 下载 Java 18。
或许这里应该和上面的推荐 Java 一起做成表格？

2024-02-04 08:39 UTC, fakeboboliu commented on app/mc.md
> +java -Xms2G -Xmx8G -server -jar ./XXX.jar nogui
或许这里可以多写一个绝对路径如何指定？
我依稀记得在 mcbbs 见到过几次被这个问题困扰的提问

2024-02-04 08:39 UTC, fakeboboliu commented on app/mc.md
> +运行一次批处理文件，此时你会发现程序立即退出，工作目录下多了一些文件，这里我们找到 `eula.txt`，在仔细阅读我的世界的 EULA 文档（见 `eula.txt` 的最顶端）后，将其中的 `false` 字样改为 `true`。
或许应该扩充一下，比如：

EULA 即 Minecraft 的用户许可协议，您在修改后即表示签署了该协议。
此认同行为表示认可 Mojang 附条件地授权您使用 Minecraft 服务端，
如不得以违法、赌博、色情、暴力等方式利用 Minecraft。
（详见 MINECRAFT 使用准则）

2024-02-04 08:39 UTC, fakeboboliu commented on app/mc.md
> +现在如果再次运行批处理文件，大概率会正常启动了，不过我们先不急着运行。
似乎很多口语化的内容，逻辑也非常口语化，
虽然我们也很喜欢轻松一点，但是这样看起来不太适宜阅读。

比如这一段如果改成：
此时服务端已经可以启动，但是请稍等，下面还有您可能需要做的事。
或者直接删除这一句话并对下面的表述稍作修改的话，似乎也不会缺少什么。

2024-02-04 08:39 UTC, fakeboboliu commented on app/mc.md
> +### 注意事项
这一段放在这里有点突兀，虽然我也没想好该怎么去放。

如果没有更多注意事项的话，似乎把这个移到上面，和配置 `server.properties` 放在一起更合适？

2024-02-04 08:52 UTC, LTHPKBTE commented
另外个人建议将 server.properties 相关配置仅在文档中提重要部分，其余做个链接到 Minecraftwiki (https://zh.minecraft.wiki/w/Server.properties#Java%E7%89%88_3)

2024-02-04 09:03 UTC, zymooll commented
> 非常感谢您的贡献， 尽管各地的教程已经很多了，但是在官方文档中包括这个话题是一段很重要的补充。
> 
> 您的文档书写风格比较随意， 为了在这篇文档的上下文中更加和谐，这个 PR 的内容需要就行文和排版做出一些修改。
> 
> 如果您愿意亲力亲为，您可以参考我的评论和其他文档进行修改； 如果您比较忙碌的话，我也可以进行一下这些修改，最终的作者名单仍然会出现您的名字。

理解，这里只是作者的一些经验之谈，不妥之处还请海涵，今天晚上我会做出修改，感谢回复！

2024-02-04 17:30 UTC, zymooll commented
这一次 commit:
1. 重写部分段落
2. 规范化用语（将 `我的世界` 替换为 `Minecraft` 来统一文章用语）

2024-02-04 17:33 UTC, zymooll commented
eula部分表述有误

2024-02-05 06:47 UTC, zymooll commented
这一次 commit：

1. 按照规范 修正有关用语中的“你“ （已经修改为“您“）

2024-02-14 16:56 UTC, fakeboboliu commented
过年好忙，明天去完医院我来慢慢整（

很抱歉拖这么久了

2024-02-14 17:09 UTC, zymooll commented
> 过年好忙，明天去完医院我来慢慢整（
> 
> 很抱歉拖这么久了

没事没事，身体要紧

2024-02-17 07:29 UTC, fakeboboliu commented
这文档看了一遍，还是会的不用看，不会的看不懂，我勉强试着改改吧，改得我血压有点高

2024-02-17 07:36 UTC, zymooll commented
> 这文档看了一遍，还是会的不用看，不会的看不懂，我勉强试着改改吧，改得我血压有点高

麻烦了！

2024-02-17 08:59 UTC, zymooll reviewed
在编辑文档方面，本人还是经验不足，曾经参与的文档编辑也只是在 OI-Wiki 项目里面修正笔误之类的，单独开一个章节这还是头遭，感谢维护者的指导和修改！

2024-02-17 10:43 UTC, fakeboboliu approved these changes

2024-02-17 10:49 UTC, fakeboboliu commented
> 在编辑文档方面，本人还是经验不足，曾经参与的文档编辑也只是在 OI-Wiki 项目里面修正笔误之类的，单独开一个章节这还是头遭，感谢维护者的指导和修改！

没事，这里也不是很严肃的场景（
有一个开始总是好的，祝你早日成为一个熟练的开源世界贡献者。

2024-02-17 10:49 UTC, merged

2024-02-17 11:01 UTC, zymooll commented
> > 在编辑文档方面，本人还是经验不足，曾经参与的文档编辑也只是在 OI-Wiki 项目里面修正笔误之类的，单独开一个章节这还是头遭，感谢维护者的指导和修改！
> 
> 没事，这里也不是很严肃的场景（ 有一个开始总是好的，祝你早日成为一个熟练的开源世界贡献者。

感谢！